* voice_vault

=voice_vault= enables you to record and archive all your meetings and
conversations with ease. Later, search through them with lightning
speed using full-text search.

=voice_vault= is a Ruby program that captures audio from the default
input and output sources using [[https://ffmpeg.org/][FFmpeg]] and then transcribes it to text
using [[https://github.com/ggerganov/whisper.cpp][whisper.cpp]]. Both the audio (mp3) and transcription will be
archived in sub-folders with this =YYYY-MM-DD_HH-MM-SS= schema.

** Installation

-  Clone the repository
-  Configure the program by editing the config.yml file in the =~/.config/voice_vault/= directory.
-  Make the script executable: chmod +x voice_vault.rb

** Usage

*** voice_vault

Simply run the script: =./voice_vault.rb=

The script will capture audio from the default input and output
sources, transcribe it to text, encode it to MP3, and save it to an
archive folder. The folder name will be in the format

#+begin_example
~/Dropbox/recordings/ find . | head -n 4
.
./2023-04-19_19-00-55
./2023-04-19_19-00-55/transcription.txt
./2023-04-19_19-00-55/recording.mp3
#+end_example

*** replicate

This uses https://replicate.com/thomasmol/whisper-diarization to
transcribe and diarize an audio file using Replicate's API.

Run the script with the required options:

#+begin_example
./replicate.rb --file_url <FILE_URL> --archive_path <ARCHIVE_PATH>
#+end_example


If you have a machine with a sufficiently strong GPU, you could also
run the same on your own hardware:

#+begin_example
docker run -d -p 5000:5000 --gpus=all r8.im/thomasmol/whisper-diarization@sha256:b9fd8313c0d492bf1ce501b3d188f945389327730773ec1deb6ef233df6ea119
curl -s -X POST \
  -H "Content-Type: application/json" \
  -d $'{
    "input": {
      "file": "https://replicate.delivery/pbxt/JcL0ttZLlbchC0tL9ZtB20phzeXCSuMm0EJNdLYElgILoZci/AI%20should%20be%20open-sourced.mp3",
      "prompt": "Mark and Lex talking about AI.",
      "file_url": "",
      "num_speakers": 2,
      "group_segments": true,
      "offset_seconds": 0,
      "transcript_output_format": "both"
    }
  }' \
  http://localhost:5000/predictions
#+end_example

*** Workflows

**** Record and transcribe locally

Use voice_vault only.

**** Record locally and transcribe + diarize remotely

Capture and process audio:

#+begin_example
./voice_vault.rb --no-transcription
# create a public url, for example with `dropbox sharelink`
./replicate.rb --file_url <path-to-wav-file> --archive_path <archive-directory>
#+end_example


This will create:

#+begin_example
~/recordings/ find . | head -n 4
.
./2023-04-19_19-00-55
./2023-04-19_19-00-55/recording.mp3
./2023-04-19_19-00-55/result_cleaned.json
./2023-04-19_19-00-55/result.json
#+end_example


** Configuration

The =config.yml= file contains the following settings:

- =whisper_path=: the path to the directory containing whisper.cpp
- =whisper_model=: the name of the model to use for speech recognition
- =whisper_threads=: the number of threads whisper.cpp will use
- =archive_path=: the path to the base directory where the MP3 and text files will be saved
- =replicate_api_token=: your API token for accessing Replicate
